#!/usr/bin/env python3

"""
Test OpenVPN servers using mihomo's native Go OpenVPN implementation via Docker.

Parses the mihomo OpenVPN YAML config (produced by enrich_maxmind.py), batches
proxies, runs them through ephemeral mihomo Docker containers, collects latency
results via the mihomo external API, and annotates the original VPN Gate
data.json with test outcomes.

No root / TUN device required because mihomo's Go OpenVPN implementation does
not create a system network interface.

Output files:
  --tested-data    data.json with a ``test`` field on each server + top-level
                   ``test`` metadata section
  --alive-mihomo   mihomo YAML containing only alive proxies, sorted by latency,
                   with ``# latency: XXXms`` comments
  --results-json   summary JSON with all statistics and per-proxy results
"""

import argparse
import json
import logging
import math
import os
import shutil
import socket
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DEFAULT_MIHOMO_INPUT = os.getenv(
    'MIHOMO_INPUT_FILE', 'public/mihomo_openvpn.yaml'
)
DEFAULT_DATA_INPUT = os.getenv(
    'TEST_DATA_INPUT_FILE', 'public/json/data.json'
)
DEFAULT_TESTED_DATA = os.getenv(
    'TESTED_DATA_FILE', 'public/json/data.tested.json'
)
DEFAULT_ALIVE_MIHOMO = os.getenv(
    'ALIVE_MIHOMO_FILE', 'public/mihomo_tested_openvpn.yaml'
)
DEFAULT_RESULTS_JSON = os.getenv(
    'RESULTS_JSON_FILE', 'public/json/test_results.json'
)
DEFAULT_MAX_ALIVE = int(os.getenv('TEST_MAX_ALIVE', '100'))
DEFAULT_BATCH_SIZE = int(os.getenv('TEST_BATCH_SIZE', '30'))
DEFAULT_CONTROLLER_PORT = int(os.getenv('TEST_CONTROLLER_PORT', '19090'))
DEFAULT_MIXED_PORT = int(os.getenv('TEST_MIXED_PORT', '17893'))
DEFAULT_BATCH_TIMEOUT = int(os.getenv('TEST_BATCH_TIMEOUT', '120'))
DEFAULT_REQUEST_TIMEOUT = float(os.getenv('TEST_REQUEST_TIMEOUT', '10'))
DEFAULT_IMAGE = os.getenv(
    'MIHOMO_DOCKER_IMAGE', 'metacubex/mihomo:latest'
)

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S',
)
logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# YAML parsing  (no PyYAML dependency)
# ---------------------------------------------------------------------------

def _parse_yaml_scalar(value: str) -> Any:
    """Parse a single YAML scalar string into a Python value.

    Handles quoted strings, booleans, null, and numeric types.
    """
    if not value:
        return value
    if value.startswith('"') and value.endswith('"'):
        return json.loads(value)
    if value.startswith("'") and value.endswith("'"):
        return value[1:-1]
    if value in ('true', 'True', 'TRUE'):
        return True
    if value in ('false', 'False', 'FALSE'):
        return False
    if value in ('null', 'Null', 'NULL', '~'):
        return None
    try:
        return int(value)
    except ValueError:
        try:
            return float(value)
        except ValueError:
            return value


def _find_colon_split(line: str) -> Optional[Tuple[str, str]]:
    """Split *line* on the first ``:`` and return ``(key, rest)``.

    Returns ``None`` when no colon is found.
    """
    colon = line.find(':')
    if colon < 0:
        return None
    return line[:colon].strip(), line[colon + 1:].strip()


def parse_mihomo_proxies(text: str) -> List[Dict[str, Any]]:
    """Parse the YAML proxy list generated by ``render_mihomo_yaml``.

    The expected format is::

        proxies:
          - name: "JP AS2516 ..."
            type: "openvpn"
            server: "203.0.113.10"
            port: 443
            ca: |-
              -----BEGIN CERTIFICATE-----
              ...
              -----END CERTIFICATE-----
            ...

    Multiline block scalars (indicated by ``|-``) are continued on lines
    indented with exactly 6 spaces.
    """
    lines = text.splitlines()
    proxies: List[Dict[str, Any]] = []
    proxy: Optional[Dict[str, Any]] = None
    multiline_key: Optional[str] = None

    def _close_multiline() -> None:
        """Finalise the current multiline value (strip trailing newline)."""
        nonlocal multiline_key
        if multiline_key is not None and proxy is not None:
            val = proxy.get(multiline_key, '')
            if val and val[-1] == '\n':
                proxy[multiline_key] = val.rstrip('\n')
            multiline_key = None

    idx = 0
    while idx < len(lines):
        raw = lines[idx]
        line = raw.rstrip()
        leading = len(raw) - len(raw.lstrip())

        # -- empty lines ---------------------------------------------------
        if not line:
            if multiline_key is not None and proxy is not None:
                proxy[multiline_key] += '\n'
            idx += 1
            continue

        # -- comment lines (inline or full-line) ---------------------------
        if line.lstrip().startswith('#'):
            idx += 1
            continue

        # -- top-level keys (no leading whitespace) ------------------------
        if leading == 0:
            idx += 1
            continue

        # -- proxy list item start: "  - " ---------------------------------
        if line.startswith('  - '):
            _close_multiline()
            if proxy is not None:
                proxies.append(proxy)
            proxy = {}
            kv = _find_colon_split(line[4:])
            if kv is not None:
                key, raw_value = kv
                if raw_value == '|-':
                    multiline_key = key
                    proxy[key] = ''
                else:
                    proxy[key] = _parse_yaml_scalar(raw_value)
            idx += 1
            continue

        # -- inside a proxy entry ------------------------------------------
        if proxy is not None:
            # Multiline continuation (6-space indent)
            if multiline_key is not None:
                if leading >= 6:
                    content = raw[6:].rstrip()
                    proxy[multiline_key] += content + '\n'
                    idx += 1
                    continue
                _close_multiline()
                # fall through to re-process this line as a new key:value

            # Key-value line: 4-space indent minimum
            rest = line.lstrip()
            kv = _find_colon_split(rest)
            if kv is not None:
                key, raw_value = kv
                if raw_value == '|-':
                    multiline_key = key
                    proxy[key] = ''
                else:
                    proxy[key] = _parse_yaml_scalar(raw_value)
                idx += 1
                continue

        idx += 1

    _close_multiline()
    if proxy is not None:
        proxies.append(proxy)

    return proxies


# ---------------------------------------------------------------------------
# YAML rendering
# ---------------------------------------------------------------------------

def format_yaml_scalar(value: Any) -> str:
    """Format a Python value as a YAML scalar (mirrors ``enrich_maxmind.py``)."""
    if isinstance(value, bool):
        return 'true' if value else 'false'
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if value is None:
        return 'null'
    return str(value)


def _render_proxy_block(proxy: Dict[str, Any], latency: Optional[int] = None) -> List[str]:
    """Render a single proxy dict as indented YAML lines.

    When *latency* is provided a comment line ``# latency: XXXms`` is
    prepended.
    """
    lines: List[str] = []
    if latency is not None:
        lines.append(f'  # latency: {latency}ms')
    items = list(proxy.items())
    for idx, (key, value) in enumerate(items):
        prefix = '  -' if idx == 0 else '   '
        if isinstance(value, str) and '\n' in value:
            lines.append(f'{prefix} {key}: |-')
            lines.extend(f'      {line}' for line in value.splitlines())
        else:
            lines.append(f'{prefix} {key}: {format_yaml_scalar(value)}')
    return lines


def render_batch_config(
    proxies: List[Dict[str, Any]],
    controller_port: int,
    mixed_port: int,
) -> str:
    """Render a complete mihomo config YAML for one batch.

    The config includes a ``url-test`` proxy-group named ``test`` so that
    the external API can be used to trigger delay tests on all proxies at
    once.
    """
    proxy_names = [p['name'] for p in proxies]

    # We produce the YAML manually to match the project convention and avoid
    # introducing a PyYAML dependency.
    parts: List[str] = []
    parts.append(f'mixed-port: {mixed_port}')
    parts.append(f'external-controller: {format_yaml_scalar(f"127.0.0.1:{controller_port}")}')
    parts.append('allow-lan: false')
    parts.append('mode: Rule')
    parts.append('log-level: silent')
    parts.append('')

    # proxy-groups
    parts.append('proxy-groups:')
    parts.append('  - name: test')
    parts.append('    type: url-test')
    parts.append('    proxies:')
    for pn in proxy_names:
        parts.append(f'      - {format_yaml_scalar(pn)}')
    parts.append(f'    url: {format_yaml_scalar("https://www.gstatic.com/generate_204")}')
    parts.append('    interval: 10')
    parts.append('')

    # proxies
    parts.append('proxies:')
    for proxy in proxies:
        parts.extend(_render_proxy_block(proxy))
    parts.append('')

    return '\n'.join(parts)


def render_alive_yaml(
    proxies_with_latency: List[Tuple[Dict[str, Any], int]],
) -> str:
    """Render the ``--alive-mihomo`` output with latency comments."""
    lines: List[str] = ['proxies:']
    for proxy, latency in proxies_with_latency:
        lines.extend(_render_proxy_block(proxy, latency=latency))
    return '\n'.join(lines) + '\n'


# ---------------------------------------------------------------------------
# Docker helpers
# ---------------------------------------------------------------------------

def check_docker() -> bool:
    """Return ``True`` iff Docker is available and the daemon is running."""
    try:
        result = subprocess.run(
            ['docker', 'info', '--format', '{{.ServerVersion}}'],
            capture_output=True,
            text=True,
            timeout=10,
        )
        return result.returncode == 0
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return False


def start_mihomo_container(
    config_path: str,
    batch_index: int,
    image: str,
    controller_port: int,
) -> Tuple[str, str]:
    """Start a mihomo Docker container, return ``(container_id, name)``."""
    container_name = f'mihomo-test-{os.getpid()}-batch{batch_index}'
    cmd = [
        'docker', 'run', '-d', '--rm',
        '--name', container_name,
        '--network', 'host',
        '-v', f'{os.path.abspath(config_path)}:/root/.config/mihomo/config.yaml',
        image,
    ]
    logger.info(
        'Starting mihomo container %s for batch %d ...',
        container_name, batch_index,
    )
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    if result.returncode != 0:
        raise RuntimeError(
            f'Docker run failed (exit {result.returncode}): '
            f'{result.stderr.strip()}'
        )
    container_id = result.stdout.strip()
    logger.info(
        'Container %s started (%s...)',
        container_name, container_id[:12],
    )
    return container_id, container_name


def stop_mihomo_container(container_name: str) -> None:
    """Forcefully stop (``docker kill``) and wait for removal (``--rm``)."""
    try:
        subprocess.run(
            ['docker', 'kill', container_name],
            capture_output=True,
            text=True,
            timeout=15,
        )
        # Wait for the --rm flag to finish removal
        subprocess.run(
            ['docker', 'wait', container_name],
            capture_output=True,
            text=True,
            timeout=15,
        )
    except subprocess.TimeoutExpired:
        logger.warning('Timeout stopping container %s', container_name)
    except Exception as exc:
        logger.warning('Error stopping container %s: %s', container_name, exc)


# ---------------------------------------------------------------------------
# Mihomo external API helpers
# ---------------------------------------------------------------------------

def _api_get(
    path: str,
    controller_port: int,
    timeout: float = DEFAULT_REQUEST_TIMEOUT,
) -> Optional[Any]:
    """GET *path* from the mihomo external controller API.

    Returns the decoded JSON response on success or ``None`` on any
    network / HTTP / parse error.
    """
    url = f'http://127.0.0.1:{controller_port}{path}'
    try:
        req = urllib.request.Request(url)
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return json.loads(resp.read().decode('utf-8'))
    except (urllib.error.URLError, urllib.error.HTTPError,
            socket.timeout, json.JSONDecodeError) as exc:
        logger.debug('API GET %s failed: %s', path, exc)
        return None


def wait_for_api(
    controller_port: int,
    timeout: float = DEFAULT_BATCH_TIMEOUT,
) -> bool:
    """Poll the mihomo API until it responds or *timeout* is reached."""
    deadline = time.time() + timeout
    poll_interval = 1.0

    while time.time() < deadline:
        result = _api_get('/proxies', controller_port, timeout=2)
        if result is not None and isinstance(result, dict):
            logger.info('Mihomo API ready on port %d', controller_port)
            return True
        time.sleep(poll_interval)

    logger.warning('Mihomo API did not become ready within %.0fs', timeout)
    return False


def run_delay_test(
    controller_port: int,
    timeout: float = DEFAULT_BATCH_TIMEOUT,
) -> Optional[Dict[str, int]]:
    """Trigger a delay test on the ``test`` proxy-group.

    Returns a mapping ``{proxy_name: latency_ms}`` for every proxy that
    responded within the per-request timeout.
    """
    url_param = urllib.parse.quote('https://www.gstatic.com/generate_204')
    path = f'/group/test/delay?url={url_param}&timeout=10000'

    deadline = time.time() + timeout
    last_result: Any = None

    while time.time() < deadline:
        result = _api_get(path, controller_port, timeout=12)
        if result is not None:
            if isinstance(result, dict):
                delays: Dict[str, int] = {}
                for name, delay_val in result.items():
                    if isinstance(delay_val, (int, float)) and delay_val > 0:
                        delays[name] = int(delay_val)
                if delays:
                    logger.info(
                        'Delay test completed: %d proxies responded',
                        len(delays),
                    )
                    return delays
                last_result = result
        time.sleep(1)

    if isinstance(last_result, dict):
        logger.warning(
            'Delay test returned but no positive delays (got %s)',
            last_result,
        )
        return last_result

    logger.warning('Delay test returned no results within %.0fs', timeout)
    return None


# ---------------------------------------------------------------------------
# Server matching helpers
# ---------------------------------------------------------------------------

def extract_hostname(proxy_name: str) -> str:
    """Extract the hostname portion from a mihomo proxy name.

    Proxy names are formatted as ``COUNTRY AS<num> hostname`` by
    ``enrich_maxmind.py``.  The hostname is always the last token.

    Example::

        >>> extract_hostname("JP AS2516 vpn.example.test")
        "vpn.example.test"
    """
    return proxy_name.rsplit(' ', 1)[-1] if ' ' in proxy_name else proxy_name


def build_proxy_to_server_map(
    servers: List[Dict[str, Any]],
    proxy_names: List[str],
) -> Dict[str, int]:
    """Map each mihomo proxy name to its index in the *servers* list.

    The lookup uses the hostname derived from the proxy name.
    Unmatched proxies are logged and omitted.
    """
    hostname_to_idx: Dict[str, int] = {}
    for idx, server in enumerate(servers):
        hostname = (
            server.get('hostname')
            or server.get('name')
            or server.get('ip')
        )
        if hostname:
            hostname_to_idx[hostname] = idx

    proxy_to_server: Dict[str, int] = {}
    for pname in proxy_names:
        hostname = extract_hostname(pname)
        idx = hostname_to_idx.get(hostname)
        if idx is not None:
            proxy_to_server[pname] = idx
        else:
            logger.warning(
                'Could not match proxy %r to any server (hostname=%r)',
                pname, hostname,
            )

    return proxy_to_server


# ---------------------------------------------------------------------------
# Statistics helpers
# ---------------------------------------------------------------------------

def compute_statistics(delays: List[int], total: int) -> Dict[str, Any]:
    """Compute summary latency statistics from test results."""
    alive = len(delays)
    dead = total - alive
    alive_rate = round(alive / total * 100, 1) if total > 0 else 0.0

    stats: Dict[str, Any] = {
        'total': total,
        'tested': total,
        'alive': alive,
        'dead': dead,
        'aliveRate': alive_rate,
    }

    if delays:
        sorted_delays = sorted(delays)
        stats['avgLatency'] = round(
            sum(sorted_delays) / len(sorted_delays), 1
        )
        stats['p50Latency'] = sorted_delays[len(sorted_delays) // 2]
        p90_idx = max(
            0, min(len(sorted_delays) - 1, int(len(sorted_delays) * 0.9))
        )
        stats['p90Latency'] = sorted_delays[p90_idx]

    return stats


# ---------------------------------------------------------------------------
# Atomic file helpers
# ---------------------------------------------------------------------------

def save_json_atomic(data: Any, path: str) -> None:
    """Write *data* as JSON to *path* using an atomic temp-file + rename."""
    dirpath = os.path.dirname(path) or '.'
    os.makedirs(dirpath, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        'w', delete=False, dir=dirpath, encoding='utf-8',
    ) as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write('\n')
        temp_path = f.name
    os.replace(temp_path, path)
    logger.info('Output saved to %s', path)


def save_text_atomic(text: str, path: str) -> None:
    """Write *text* to *path* using an atomic temp-file + rename."""
    dirpath = os.path.dirname(path) or '.'
    os.makedirs(dirpath, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        'w', delete=False, dir=dirpath, encoding='utf-8',
    ) as f:
        f.write(text)
        temp_path = f.name
    os.replace(temp_path, path)
    logger.info('Output saved to %s', path)


# ---------------------------------------------------------------------------
# Batch processing
# ---------------------------------------------------------------------------

def run_batch(
    batch_proxies: List[Dict[str, Any]],
    batch_index: int,
    image: str,
    controller_port: int,
    mixed_port: int,
    batch_timeout: int,
) -> Dict[str, int]:
    """Run a single batch of proxies through an ephemeral mihomo container.

    Returns ``{proxy_name: latency_ms}`` for proxies that responded.
    The container is always cleaned up (try/finally).
    """
    config_yaml = render_batch_config(
        batch_proxies, controller_port, mixed_port,
    )
    container_name: Optional[str] = None
    temp_dir: Optional[str] = None

    try:
        # Write the config to a temporary file that will be mounted into the
        # container.
        temp_dir = tempfile.mkdtemp(prefix='mihomo-batch-')
        config_path = os.path.join(temp_dir, 'config.yaml')
        with open(config_path, 'w', encoding='utf-8') as f:
            f.write(config_yaml)

        _, container_name = start_mihomo_container(
            config_path, batch_index, image, controller_port,
        )

        if not wait_for_api(controller_port, timeout=batch_timeout):
            logger.warning(
                'Batch %d: API did not become ready, skipping',
                batch_index,
            )
            return {}

        results = run_delay_test(controller_port, timeout=batch_timeout)
        if results is None:
            logger.warning(
                'Batch %d: delay test produced no results',
                batch_index,
            )
            return {}

        return results

    finally:
        if container_name is not None:
            stop_mihomo_container(container_name)
        if temp_dir is not None:
            shutil.rmtree(temp_dir, ignore_errors=True)


def process_all_proxies(
    proxies: List[Dict[str, Any]],
    batch_size: int,
    image: str,
    controller_port: int,
    mixed_port: int,
    batch_timeout: int,
) -> Dict[str, int]:
    """Test all *proxies* in batches, returning ``{name: latency_ms}``."""
    all_results: Dict[str, int] = {}
    total_batches = math.ceil(len(proxies) / batch_size)

    for batch_idx in range(total_batches):
        start = batch_idx * batch_size
        end = min(start + batch_size, len(proxies))
        batch = proxies[start:end]

        logger.info(
            'Batch %d/%d: testing %d proxies (indices %d-%d)',
            batch_idx + 1, total_batches, len(batch), start, end - 1,
        )

        results = run_batch(
            batch, batch_idx,
            image, controller_port, mixed_port, batch_timeout,
        )
        all_results.update(results)

        alive_so_far = len(all_results)
        tested_so_far = min(end, len(proxies))
        pct = (
            alive_so_far / tested_so_far * 100
            if tested_so_far > 0 else 0.0
        )
        logger.info(
            'Progress: %d/%d alive (%.1f%%)',
            alive_so_far, tested_so_far, pct,
        )

    return all_results


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args(argv: Optional[List[str]] = None) -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description=(
            'Test OpenVPN servers using mihomo Docker containers. '
            'Parses the mihomo YAML from --mihomo-input, batches proxies, '
            'runs them through mihomo containers, and annotates data.json '
            'with test results.'
        ),
    )
    parser.add_argument(
        '--mihomo-input',
        default=DEFAULT_MIHOMO_INPUT,
        help=f'Input mihomo OpenVPN YAML path (default: {DEFAULT_MIHOMO_INPUT})',
    )
    parser.add_argument(
        '--data-input',
        default=DEFAULT_DATA_INPUT,
        help=f'Input VPN Gate data.json path (default: {DEFAULT_DATA_INPUT})',
    )
    parser.add_argument(
        '--tested-data',
        default=DEFAULT_TESTED_DATA,
        help=(
            'Output data.json annotated with test field '
            f'(default: {DEFAULT_TESTED_DATA})'
        ),
    )
    parser.add_argument(
        '--alive-mihomo',
        default=DEFAULT_ALIVE_MIHOMO,
        help=(
            'Output YAML containing only alive proxies sorted by latency '
            f'(default: {DEFAULT_ALIVE_MIHOMO})'
        ),
    )
    parser.add_argument(
        '--results-json',
        default=DEFAULT_RESULTS_JSON,
        help=(
            'Output JSON with test summary statistics and per-proxy results '
            f'(default: {DEFAULT_RESULTS_JSON})'
        ),
    )
    parser.add_argument(
        '--max-alive',
        type=int,
        default=DEFAULT_MAX_ALIVE,
        help=(
            'Maximum number of alive proxies to include in --alive-mihomo '
            f'output (default: {DEFAULT_MAX_ALIVE})'
        ),
    )
    parser.add_argument(
        '--batch-size',
        type=int,
        default=DEFAULT_BATCH_SIZE,
        help=(
            'Number of proxies to test per mihomo batch '
            f'(default: {DEFAULT_BATCH_SIZE})'
        ),
    )
    parser.add_argument(
        '--docker-image',
        default=DEFAULT_IMAGE,
        help=(
            'mihomo Docker image to use '
            f'(default: {DEFAULT_IMAGE})'
        ),
    )
    parser.add_argument(
        '--controller-port',
        type=int,
        default=DEFAULT_CONTROLLER_PORT,
        help=(
            'Port for the mihomo external controller API '
            f'(default: {DEFAULT_CONTROLLER_PORT})'
        ),
    )
    parser.add_argument(
        '--mixed-port',
        type=int,
        default=DEFAULT_MIXED_PORT,
        help=(
            'Mixed port for the mihomo proxy '
            f'(default: {DEFAULT_MIXED_PORT})'
        ),
    )
    parser.add_argument(
        '--batch-timeout',
        type=int,
        default=DEFAULT_BATCH_TIMEOUT,
        help=(
            'Maximum seconds to wait for a single batch '
            f'(default: {DEFAULT_BATCH_TIMEOUT})'
        ),
    )
    return parser.parse_args(argv)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main(argv: Optional[List[str]] = None) -> None:
    """Entry point for ``scripts/test_openvpn.py``."""
    args = parse_args(argv)

    # -- Docker availability check -----------------------------------------
    if not check_docker():
        logger.warning(
            'Docker is not available or the daemon is not running. '
            'Skipping OpenVPN testing.',
        )
        sys.exit(0)

    # -- Read input files --------------------------------------------------
    logger.info('Reading mihomo YAML from %s', args.mihomo_input)
    with open(args.mihomo_input, 'r', encoding='utf-8') as f:
        yaml_text = f.read()

    proxies = parse_mihomo_proxies(yaml_text)
    logger.info('Parsed %d proxies from mihomo YAML', len(proxies))

    if not proxies:
        logger.warning('No proxies found in mihomo YAML. Nothing to test.')
        sys.exit(0)

    logger.info('Reading VPN Gate data from %s', args.data_input)
    with open(args.data_input, 'r', encoding='utf-8') as f:
        vpn_data = json.load(f)

    servers: List[Dict[str, Any]] = (
        vpn_data.get('data', {}).get('servers', [])
    )
    logger.info('Loaded %d servers from data.json', len(servers))

    # -- Build proxy-name to server-index mapping --------------------------
    proxy_names = [p['name'] for p in proxies]
    proxy_to_server = build_proxy_to_server_map(servers, proxy_names)

    # -- Run tests ---------------------------------------------------------
    results = process_all_proxies(
        proxies,
        batch_size=args.batch_size,
        image=args.docker_image,
        controller_port=args.controller_port,
        mixed_port=args.mixed_port,
        batch_timeout=args.batch_timeout,
    )
    logger.info(
        'Testing complete: %d proxies alive out of %d',
        len(results), len(proxies),
    )

    # -- Timestamp ---------------------------------------------------------
    now_iso = (
        datetime.now(timezone.utc)
        .isoformat(timespec='milliseconds')
        .replace('+00:00', 'Z')
    )

    # -- Annotate servers --------------------------------------------------
    all_delays: List[int] = []

    # Mark alive servers
    for proxy_name, delay in results.items():
        server_idx = proxy_to_server.get(proxy_name)
        if server_idx is None:
            logger.debug(
                'Skipping annotation for unmatched proxy: %s', proxy_name,
            )
            continue
        servers[server_idx]['test'] = {
            'alive': True,
            'latencyMs': delay,
            'testedAt': now_iso,
        }
        all_delays.append(delay)

    # Mark tested-but-dead servers
    tested_names = set(results.keys())
    for proxy_name in proxy_names:
        if proxy_name in tested_names:
            continue
        server_idx = proxy_to_server.get(proxy_name)
        if server_idx is None:
            continue
        servers[server_idx]['test'] = {
            'alive': False,
            'latencyMs': None,
            'testedAt': now_iso,
        }

    # -- Statistics --------------------------------------------------------
    stats = compute_statistics(all_delays, len(proxies))

    # -- Top-level test metadata in data.json ------------------------------
    vpn_data['test'] = {
        'generatedAt': now_iso,
        'statistics': stats,
    }

    # -- Save outputs ------------------------------------------------------

    # 1. Tested data.json
    save_json_atomic(vpn_data, args.tested_data)

    # 2. Results JSON (includes both summary and per-proxy details)
    results_data: Dict[str, Any] = {
        'generatedAt': now_iso,
        'statistics': stats,
        'results': [
            {'proxyName': name, 'latencyMs': delay}
            for name, delay in sorted(
                results.items(), key=lambda x: x[1],
            )
        ],
    }
    save_json_atomic(results_data, args.results_json)

    # 3. Alive mihomo YAML (sorted by latency, limited to max-alive)
    alive_with_latency: List[Tuple[Dict[str, Any], int]] = []
    for proxy in proxies:
        pname = proxy['name']
        if pname in results:
            alive_with_latency.append((proxy, results[pname]))
    alive_with_latency.sort(key=lambda x: x[1])
    alive_with_latency = alive_with_latency[:args.max_alive]

    alive_yaml = render_alive_yaml(alive_with_latency)
    save_text_atomic(alive_yaml, args.alive_mihomo)

    # -- Summary to log ----------------------------------------------------
    logger.info(
        'Results: %d total, %d alive, %d dead (%.1f%% alive rate)',
        stats['total'], stats['alive'], stats['dead'], stats['aliveRate'],
    )
    if all_delays:
        logger.info(
            'Latency: avg=%.0fms  p50=%dms  p90=%dms',
            stats['avgLatency'], stats['p50Latency'], stats['p90Latency'],
        )


if __name__ == '__main__':
    main()
